### ISSUE TITLE
コマンドが文中にあり、実行の忘れが発生する。

### ISSUE THREAD

**Issue by ogom** [railsgirls-jp/coach.info#1]
## バージョン
- OS: 共通
- Ruby: 共通
- Rails: 共通
## 問題の背景

**Heroku に Rails アプリをアップ**で**アプリのデプロイ**の**データベースのマイグレート**で
`heroku run rake db:migrate`のコマンドを実行を忘れた。

http://railsgirls.jp/heroku/
## 問題の詳細

`rake db:migrate`のコマンドを実行を忘れると、`heroku logs`でデバックをして
原因を解決する必要がある。
## 解決方法

コマンドはアイコンとコードにしたほうがよい。

```
heroku run rake db:migrate
```

このようにコマンドをまとめていた方が、読みやすいかもしれません。
https://github.com/hommachirb/railsgirls/blob/master/doc/lesson/002.md#deploy

**Comment by satomicchy** [comment]
@ogom READMEにあるとおり、OS等の情報を書いてください。OS共通事項なら、その旨明記をお願いいたします。

**Comment by ogom** [comment]
@satomicchy 申し訳ございません。

Issueのテンプレートを作成しましたのでご利用ください。
こちらをクリックするとIssueでテンプレートが適応されます。
https://github.com/railsgirls-jp/coach.info/issues/new?title=%5B問題%5D&body=%23%23%20バージョン%0A%2a%20OS:%20共通%0A%2a%20Ruby:%20共通%0A%2a%20Rails:%20共通%0A%0A%23%23%20問題の背景%0A%0A%23%23%20問題の詳細%0A%0A%23%23%20解決方法%0A%0A

**Comment by satomicchy** [comment]
@ogom ありがとうございます！テンプレート素敵です。READMEに貼っておきたいと思います。（Labelを設定したのと、共通化したかったので、ちょっと変えました。）

**Comment by ogom** [comment]
対応ありがとうございます。
