### ISSUE TITLE
ワークショップで使うコマンド一覧を準備する

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/coach.info#17]
名古屋のKPT で ワークショップで使うコマンドを紙に印刷しておいたらよかったのでは? というのがあったので、
本家 materials のように、準備しておいたら、各地で使えると思いますので、
準備しようと思います。

@yada-ITA 前回使ったものでもよいので、サンプルとかお持ちでしょうか？

**Comment by springaki** [comment]
コレですかね？
https://github.com/railsgirls-jp/nagoya/blob/master/materials/Command_Cheatsheet.pdf

ずいぶん前にシェアしてくれて、毎回印刷もしてくれていたのですが、今回持ってくるのを忘れたという話しを聞いたような...w

**Comment by springaki** [comment]
コレもしかして Nagoya team に入ってる人しか見えないのか... 置き場所考えた方が良さそうですね。

**Comment by emorima** [comment]
@springaki ありがとうございます!

本家に合わせて、JP用の Materials のページを作って、
そこに置いておくようにしたら、どうでしょうか？

**Comment by springaki** [comment]
@emorima material 容量大きくなりますもんね。賛成ですー。
使う人の為にライセンス (誰でも自由に使っていいよ的なのを) 書いておくといいかもしれないですねー。 (もちろん リソース提供者の許可をもらって)

**Comment by springaki** [comment]
本家の materials は private だった。

**Comment by emorima** [comment]
https://github.com/railsgirls-jp/materials

こちらに作成し、UPしてあります。
