### ISSUE TITLE
heroku open で開かれる URL だと CSS が読み込まれない

### ISSUE THREAD

**Issue by suzuki-kei** [railsgirls-jp/coach.info#8]
## バージョン
- OS:共通
- Ruby:共通
- Rails:共通
## 背景

`heroku open` で開かれる URL (http) だと CSS が読み込まれませんでした。
## 解決方法など

URL のプロトコルを https に変更してアクセスし直しました。

**Comment by sho-h** [comment]
本Issueですが、僕は`heroku open`時に開かれるのがhttpsで、URLを直接httpに変更したら表示できました。

原因ですが、railsgirls.comの証明書が2013年には切れてるため、application.html.erbの以下の部分がうまく取得できないのだと思いました。

```
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  ...
  <script src="//railsgirls.com/assets/bootstrap.js"></script>
```

なお、[既にIssue](https://github.com/railsgirls/railsgirls.github.com/issues/261)も挙がっているようですがレスがないようですね。最近の事のようなので対応される見込みがないとは言い切れませんが、証明書の方は2年放置なのでjpの方にcssを置いちゃうとか、他のところにリンクしてこのIssueはcloseする方向に持っていくのがいいように思いました。

**Comment by sho-h** [comment]
[昔](https://github.com/jasinai/railsgirls.github.com/commit/0e3ac190654374e33d17995614eb5620dd9c4db2)はよそにリンクしてた時もあったようなのでよそにリンクでも貼る方向でPullRequestだそうかと思いました。(少し待っていや、jpに置こうぜという意見がなければ)

**Comment by suzuki-kei** [comment]
ご対応ありがとうございます！

> railsgirls.comの証明書が2013年には切れてる
> 切ない・・

**Comment by springaki** [comment]
@suzuki-kei この件 OKそうならcloseお願いします :smile_cat:

**Comment by suzuki-kei** [comment]
close します！ :paw_prints:

**Comment by springaki** [comment]
@suzuki-kei ありがとうございます !! :octocat:
